type Artifact {
  """The file name of the artifact"""
  name: String!

  """The download URL for the artifact"""
  url: Url!

  """The MIME type of the artifact data"""
  mimeType: String!
}

scalar Creator

"""
Implement the DateTime<Utc> scalar

The input/output is a string in RFC3339 format.
"""
scalar DateTime

"""
The `JSON` scalar type represents JSON values as specified by [ECMA-404](https://ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf).
"""
scalar JSON

"""A scalar that can represent any JSON Object value."""
scalar JSONObject

"""A single log line streamed from a pod"""
type LogEntry {
  """The log line content"""
  content: String!

  """The name of the pod producing the log"""
  podName: String!
}

"""The root mutation of the service"""
type Mutation {
  """submit specific workflow template"""
  submitWorkflowTemplate(name: String!, visit: VisitInput!, parameters: JSON!): Workflow!
  createExperimentDefinition(input: CreateExperimentDefinitionInput!): ExperimentDefinition
  experimentDefinition(id: UUID!): ExperimentDefinitionMutations
  createInstrumentSession(input: CreateInstrumentSessionInput!): InstrumentSession!
  instrumentSession(proposalNumber: Int!, instrumentSessionNumber: Int!): InstrumentSessionMutations
  createOrValidateSamples(input: CreateOrValidateSampleInput!): CreateSamplesResponse!
  createSamples(input: CreateSampleInput!): [Sample!]! @deprecated(reason: "Will be replaced by createOrValidateSamples")
  sample(sampleId: UUID!): SampleMutations
}

"""Represents Relay Node types"""
union NodeValue = Workflow

"""Information about pagination in a connection"""
type PageInfo {
  """When paginating backwards, are there more items?"""
  hasPreviousPage: Boolean!

  """When paginating forwards, are there more items?"""
  hasNextPage: Boolean!

  """When paginating backwards, the cursor to continue."""
  startCursor: String

  """When paginating forwards, the cursor to continue."""
  endCursor: String
}

"""The root query of the service"""
type Query {
  node(id: ID!): NodeValue

  """Get a single [`Workflow`] by proposal, visit, and name"""
  workflow(visit: VisitInput!, name: String!): Workflow!

  """Find all workflows available for a given visit"""
  workflows(visit: VisitInput!, cursor: String, limit: Int, filter: WorkflowFilter): WorkflowConnection!

  """Retrieves a single cluster workflow template by name"""
  workflowTemplate(name: String!): WorkflowTemplate!

  """
  Retrieves all cluster workflow templates with respective pagination data
  """
  workflowTemplates(cursor: String, limit: Int, filter: WorkflowTemplatesFilter): WorkflowTemplateConnection!
  jsonSchema(url: String!): JSONSchema
  jsonSchemas(type: String = null, instrument: String = null): [JSONSchema!]!
  experimentDefinition(id: UUID!): ExperimentDefinition
  experimentDefinitions(instrumentSessions: [InstrumentSessionInput!]!, first: Int = null, last: Int = null, after: String = null, before: String = null): ExperimentDefinitionConnection
  experiment(id: UUID!): Experiment
  experiments(instrumentSessions: [InstrumentSessionInput!]!, first: Int = null, last: Int = null, after: String = null, before: String = null): ExperimentConnection

  """Get a proposal by its number"""
  proposal(proposalNumber: Int!): Proposal

  """Get a list of proposals"""
  proposals(first: Int = null, last: Int = null, after: String = null, before: String = null, sortBy: [ProposalSortInput!] = null, filterBy: ProposalFilterInput = null): ProposalConnection!

  """
  Get a proposal by its reference string e.g. 'MX12345'. The lookup is case-insensitive.
  """
  proposalByReference(reference: String!): Proposal

  """Get a instrument session"""
  instrumentSession(proposalNumber: Int!, instrumentSessionNumber: Int!): InstrumentSession

  """
  Get an instrument session by its reference string e.g. 'MX12345-1'. The lookup is case-insensitive.
  """
  instrumentSessionByReference(reference: String!): InstrumentSession

  """Get a list of instrument sessions"""
  instrumentSessions(proposalNumber: Int = null, proposalCategory: String = null, first: Int = null, last: Int = null, after: String = null, before: String = null, sortBy: [InstrumentSessionSortInput!] = null, filterBy: InstrumentSessionFilterInput = null): InstrumentSessionConnection!

  """Get an instrument by name"""
  instrumentByName(name: String!): Instrument

  """Get an instrument by key"""
  instrumentByKey(key: String!): Instrument

  """Get a list of instruments"""
  instruments(scienceGroup: String = null): [Instrument!]!

  """Get an account"""
  account(username: String!): Account

  """Get a sample by its id"""
  sample(sampleId: UUID!): Sample

  """Get a list of samples associated with a given instrument session"""
  samples(first: Int!, instrumentSessions: [InstrumentSessionInput!] = null, filter: SampleFilterInput! = {schemaUrl: null, createdTime: null, updatedTime: null, name: null, data: null}, before: String = null, after: String = null, last: Int = null, orderBy: SampleOrder! = {name: null, createdTime: null, updatedTime: null}): SampleConnection!
}

"""Supported DLS science groups"""
enum ScienceGroup {
  """Macromolecular Crystallography"""
  MX

  """Workflows Examples"""
  EXAMPLES

  """Magnetic Materials"""
  MAGNETIC_MATERIALS

  """Soft Condensed Matter"""
  CONDENSED_MATTER

  """Imaging and Microscopy"""
  IMAGING

  """Biological Cryo-Imaging"""
  BIO_CRYO_IMAGING

  """Structures and Surfaces"""
  SURFACES

  """Crystallography"""
  CRYSTALLOGRAPHY

  """Spectroscopy"""
  SPECTROSCOPY
}

"""The root mutation of the service"""
type Subscription {
  """Processing to subscribe to logs for a single pod of a workflow"""
  logs(visit: VisitInput!, workflowName: String!, taskId: String!): LogEntry!

  """Processing to subscribe to data for all workflows in a session"""
  workflow(visit: VisitInput!, name: String!): Workflow!
}

type Task {
  """Unique name of the task"""
  id: String!

  """Display name of the task"""
  name: String!

  """Current status of a task"""
  status: TaskStatus!

  """Parent of a task"""
  depends: [String!]!

  """Children of a task"""
  dependencies: [String!]!

  """Artifacts produced by a task"""
  artifacts: [Artifact!]!

  """Node type - Pod, DAG, etc"""
  stepType: String!

  """Start time for a task on a workflow"""
  startTime: DateTime

  """End time for a task on a workflow"""
  endTime: DateTime

  """
  A human readable message indicating details about why this step is in this condition
  """
  message: String
}

enum TaskStatus {
  PENDING
  RUNNING
  SUCCEEDED
  SKIPPED
  FAILED
  ERROR
  OMITTED
}

scalar Template

"""Information about where the template is stored"""
type TemplateSource {
  """The URL of the GitHub repository"""
  repositoryUrl: String!

  """The path to the template within the repository"""
  path: String!

  """The current tracked branch of the repository"""
  targetRevision: String!
}

"""
URL is a String implementing the [URL Standard](http://url.spec.whatwg.org/)
"""
scalar Url

"""A visit to an instrument as part of a session"""
type Visit {
  """Project Proposal Code"""
  proposalCode: String!

  """Project Proposal Number"""
  proposalNumber: Int!

  """Session visit Number"""
  number: Int!
}

"""A visit to an instrument as part of a session"""
input VisitInput {
  """Project Proposal Code"""
  proposalCode: String!

  """Project Proposal Number"""
  proposalNumber: Int!

  """Session visit Number"""
  number: Int!
}

type Workflow {
  """The unique ID derived from the visit and name"""
  id: ID!

  """The name given to the workflow, unique within a given visit"""
  name: String!

  """The visit the Workflow was run against"""
  visit: Visit!

  """The current status of the workflow"""
  status: WorkflowStatus

  """The top-level workflow parameters"""
  parameters: JSONObject

  """The name of the template used to run the workflow"""
  templateRef: String

  """The workflow creator"""
  creator: WorkflowCreator!
}

type WorkflowConnection {
  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """A list of edges."""
  edges: [WorkflowEdge!]!

  """A list of nodes."""
  nodes: [Workflow!]!
}

"""Information about the creator of a workflow."""
type WorkflowCreator {
  """
  An identifier unique to the creator of the workflow.
  Typically this is the creator's Fed-ID.
  """
  creatorId: String!
}

"""An edge in a connection."""
type WorkflowEdge {
  """The item at the end of the edge"""
  node: Workflow!

  """A cursor for use in pagination"""
  cursor: String!
}

"""All tasks in the workflow have errored"""
type WorkflowErroredStatus {
  """Time at which this workflow started"""
  startTime: DateTime!

  """Time at which this workflow completed"""
  endTime: DateTime!

  """
  A human readable message indicating details about why the workflow is in this condition
  """
  message: String

  """Tasks created by the workflow"""
  tasks: [Task!]!
}

"""All tasks in the workflow have failed"""
type WorkflowFailedStatus {
  """Time at which this workflow started"""
  startTime: DateTime!

  """Time at which this workflow completed"""
  endTime: DateTime!

  """
  A human readable message indicating details about why the workflow is in this condition
  """
  message: String

  """Tasks created by the workflow"""
  tasks: [Task!]!
}

"""All the supported Workflows filters"""
input WorkflowFilter {
  """The status field for a workflow"""
  workflowStatusFilter: WorkflowStatusFilter

  """The fedid of the user who created the workflow"""
  creator: Creator

  """The name of the workflow template"""
  template: Template
}

type WorkflowPendingStatus {
  """
  A human readable message indicating details about why the workflow is in this condition
  """
  message: String
}

type WorkflowRunningStatus {
  """Time at which this workflow started"""
  startTime: DateTime!

  """
  A human readable message indicating details about why the workflow is in this condition
  """
  message: String

  """Tasks created by the workflow"""
  tasks: [Task!]!
}

"""The status of a workflow"""
union WorkflowStatus = WorkflowPendingStatus | WorkflowRunningStatus | WorkflowSucceededStatus | WorkflowFailedStatus | WorkflowErroredStatus

"""Represents workflow status filters"""
input WorkflowStatusFilter {
  pending: Boolean! = false
  running: Boolean! = false
  succeeded: Boolean! = false
  failed: Boolean! = false
  error: Boolean! = false
}

"""All tasks in the workflow have succeded"""
type WorkflowSucceededStatus {
  """Time at which this workflow started"""
  startTime: DateTime!

  """Time at which this workflow completed"""
  endTime: DateTime!

  """
  A human readable message indicating details about why the workflow is in this condition
  """
  message: String

  """Tasks created by the workflow"""
  tasks: [Task!]!
}

type WorkflowTemplate {
  """The name given to the workflow template, globally unique"""
  name: String!

  """The group who maintains the workflow template"""
  maintainer: String!

  """A human readable title for the workflow template"""
  title: String

  """A human readable description of the workflow which is created"""
  description: String

  """The repository storing the code associated with this template."""
  repository: String

  """A JSON Schema describing the arguments of a Workflow Template"""
  arguments: JSON!

  """
  A JSON Forms UI Schema describing how to render the arguments of the Workflow Template
  """
  uiSchema: JSON

  """Information about where the template is obtained from"""
  templateSource: TemplateSource
}

type WorkflowTemplateConnection {
  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """A list of edges."""
  edges: [WorkflowTemplateEdge!]!

  """A list of nodes."""
  nodes: [WorkflowTemplate!]!
}

"""An edge in a connection."""
type WorkflowTemplateEdge {
  """The item at the end of the edge"""
  node: WorkflowTemplate!

  """A cursor for use in pagination"""
  cursor: String!
}

"""Supported label filters for ClusterWorkflowTemplates"""
input WorkflowTemplatesFilter {
  """The science group owning the template eg imaging"""
  scienceGroup: [ScienceGroup!]
}

"""A JSON schema"""
type JSONSchema {
  """The identifier of the schema"""
  id: String!

  """A URL from which the schema can be accessed"""
  url: String!

  """The type of object the shema describes (if known)"""
  type: String

  """The title of the schema"""
  title: String

  """The version of the schema"""
  version: String

  """The instrument the schema was created for"""
  instrument: String

  """The description og the schema"""
  description: String
}

"""Values required to create an experiment definition"""
input CreateExperimentDefinitionInput {
  name: String!
  data: JSON!
  dataSchemaUrl: String!
  proposalNumber: Int!
  instrumentSessionNumber: Int!
}

"""Values required for the createExperiments mutation"""
input CreateExperimentsInput {
  experiments: [ExperimentInput!]!
}

type Experiment {
  id: UUID!
  name: String!
  createdTime: DateTime!
  updatedTime: DateTime!
  experimentDefinition: ExperimentDefinition!

  """The sample that this experiment is associated with"""
  sample: Sample!
}

type ExperimentConnection {
  edges: [ExperimentEdge!]!
  pageInfo: PageInfo!
}

type ExperimentDefinition {
  id: UUID!
  name: String!
  createdTime: DateTime!
  updatedTime: DateTime!
  data: JSON!
  dataSchemaUrl: String!
  proposalNumber: Int!
  instrumentSessionNumber: Int!

  """
  The instrument session that this experiment definition is associated with
  """
  instrumentSession: InstrumentSession!

  """Experiments associated with this experiment definition"""
  experiments: [Experiment!]!
}

type ExperimentDefinitionConnection {
  edges: [ExperimentDefinitionEdge!]!
  pageInfo: PageInfo!
}

type ExperimentDefinitionEdge {
  cursor: String!
  node: ExperimentDefinition!
}

"""Mutations for a given experiment defintion"""
type ExperimentDefinitionMutations {
  createExperiments(input: CreateExperimentsInput!): [Experiment!]!
}

type ExperimentEdge {
  cursor: String!
  node: Experiment!
}

"""Values required to create an experiment"""
input ExperimentInput {
  name: String!
  sampleId: UUID!
}

type InstrumentSession {
  instrumentSessionNumber: Int!
  proposal: Proposal

  """Experiment Definitions"""
  experimentDefinitions(first: Int = null, last: Int = null, after: String = null, before: String = null): ExperimentDefinitionConnection!

  """Experiments associated with this session"""
  experiments(first: Int = null, last: Int = null, after: String = null, before: String = null): ExperimentConnection!
  instrumentSessionId: Int! @deprecated(reason: "instrument_session_id is deprecated and will be removed in a future version.")
  startTime: DateTime
  endTime: DateTime
  type: String
  state: String
  riskRating: String

  """
  A human-readable reference for this session in the form '<PROPOSALCATEGORY><PROPOSALNUMBER>-<SESSIONNUMBER>' e.g. 'MX12345-1'.
  """
  instrumentSessionReference: String
  instrument: Instrument!
  roles: [InstrumentSessionRole!]!

  """Samples associated with a given instrument session"""
  samples(first: Int!, filter: SampleFilterInput! = {schemaUrl: null, createdTime: null, updatedTime: null, name: null, data: null}, before: String = null, after: String = null, last: Int = null, orderBy: SampleOrder! = {name: null, createdTime: null, updatedTime: null}): SampleConnection!
}

"""Values required to uniquely identify an instrument session"""
input InstrumentSessionInput {
  proposalNumber: Int!
  instrumentSessionNumber: Int!
}

type Proposal {
  proposalNumber: Int!
  proposalCategory: String
  title: String
  summary: String
  state: ProposalState!

  """
  A human-readable reference for this proposal in the form '<PROPOSALCATEGORY><PROPOSALNUMBER>' e.g. 'MX12345'.
  """
  proposalReference: String
  instrumentSessions: [InstrumentSession!]!
  instruments: [Instrument!]!
  roles: [ProposalAccount!]!
}

type Sample {
  id: UUID!
  experiments: [Experiment!]!
  name: String!
  data: JSON!
  createdTime: DateTime!
  updatedTime: DateTime!
  dataSchemaUrl: String!

  """Samples from which this sample is derived"""
  parents(first: Int = null, before: String = null, after: String = null, last: Int = null): SampleConnection!

  """Samples derived from this sample"""
  children(first: Int = null, before: String = null, after: String = null, last: Int = null): SampleConnection!

  """Events linked to this sample"""
  events(first: Int = null, before: String = null, after: String = null, last: Int = null): SampleEventConnection!

  """The JSON schema that the sample's `data` conforms to"""
  dataSchema: JSON!

  """The instrument sessions that this sample is associated with"""
  instrumentSessions: [InstrumentSession!]!
  images: [SampleImage!]!
}

scalar UUID

type Account {
  accountId: Int! @deprecated(reason: "account_id is deprecated and will be removed in a future version.")
  username: String!
  emailAddress: String
  title: String
  givenName: String
  familyName: String
  type: AccountType!
  state: AccountState!
  proposalRoles: [ProposalAccount!]!
  instrumentSessionRoles: [InstrumentSessionRole!]!
}

enum AccountState {
  enabled
  disabled
}

enum AccountType {
  user
  staff
  functional
}

input CreateInstrumentSessionInput {
  """Number of the proposal the session is for"""
  proposalNumber: Int!

  """Name of the instrument the session is for"""
  instrumentName: String!

  """
  Instrument Session information that isn't needed by the Session Service but should be passed through the UAS
  """
  sessionInfo: String!
}

input DateTimeFilterInput {
  eq: DateTime = null
  neq: DateTime = null
  gt: DateTime = null
  lt: DateTime = null
  gte: DateTime = null
  lte: DateTime = null
}

type Instrument {
  name: String!
  key: String!
  scienceGroup: String
  description: String
  proposals: [Proposal!]!
  instrumentSessions: [InstrumentSession!]!
}

type InstrumentSessionConnection {
  edges: [InstrumentSessionEdge!]!
  pageInfo: PageInfo!
}

type InstrumentSessionEdge {
  cursor: String!
  node: InstrumentSession!
}

input InstrumentSessionFilterInput {
  instrumentSessionNumber: IntFilterInput = null
  startTime: DateTimeFilterInput = null
  endTime: DateTimeFilterInput = null
  type: StringFilterInput = null
  state: InstrumentSessionStateFilterInput = null
  riskRating: StringFilterInput = null
  proposalNumber: IntFilterInput = null
}

type InstrumentSessionMutations {
  instrumentSessionNumber: Int!
  proposalNumber: Int!

  """Create or validate samples associated with this instrument session"""
  createOrValidateSamples(input: CreateOrValidateSampleInputBase!): CreateSamplesResponse!
}

type InstrumentSessionRole {
  instrumentSession: InstrumentSession!
  account: Account!
  role: String!
  onSite: Boolean!
}

enum InstrumentSessionSortField {
  instrumentSessionNumber
  startTime
  endTime
  type
  state
  riskRating
  proposalNumber
}

input InstrumentSessionSortInput {
  field: InstrumentSessionSortField!
  orderBy: SortOrder!
}

enum InstrumentSessionState {
  CANCELLED
  COMPLETED
  FUTURE
  IN_PROGRESS
}

input InstrumentSessionStateFilterInput {
  eq: InstrumentSessionState = null
  neq: InstrumentSessionState = null
}

input IntFilterInput {
  eq: Int = null
  neq: Int = null
  gt: Int = null
  lt: Int = null
  gte: Int = null
  lte: Int = null
}

type ProposalAccount {
  proposal: Proposal!
  account: Account!
  role: String!
}

type ProposalConnection {
  edges: [ProposalEdge!]!
  pageInfo: PageInfo!
}

type ProposalEdge {
  cursor: String!
  node: Proposal!
}

input ProposalFilterInput {
  proposalNumber: IntFilterInput = null
  proposalCategory: StringFilterInput = null
  title: StringFilterInput = null
  state: ProposalStateFilterInput = null
}

enum ProposalSortField {
  proposalNumber
}

input ProposalSortInput {
  field: ProposalSortField!
  orderBy: SortOrder!
}

enum ProposalState {
  OPEN
  CLOSED
  CANCELLED
}

input ProposalStateFilterInput {
  eq: ProposalState = null
  neq: ProposalState = null
}

enum SortOrder {
  ASC
  DESC
}

input StringFilterInput {
  eq: String = null
  neq: String = null
  contains: String = null
  notContains: String = null
  startsWith: String = null
  endsWith: String = null
}

input AddSampleEventInput {
  description: String!
}

input CreateOrValidateSampleInput {
  """URL of the JSON schema the samples' `data` should be validated against"""
  dataSchemaUrl: String!

  """Samples to be created"""
  samples: [SampleIn!]!

  """
  Whether or not the provided samples should only be validated and not created
  """
  validateOnly: Boolean! = false

  """Number of the proposal the samples should be associated with"""
  proposalNumber: Int!

  """Number of the instrument session the samples should be associated with"""
  instrumentSessionNumber: Int!
}

input CreateOrValidateSampleInputBase {
  """URL of the JSON schema the samples' `data` should be validated against"""
  dataSchemaUrl: String!

  """Samples to be created"""
  samples: [SampleIn!]!

  """
  Whether or not the provided samples should only be validated and not created
  """
  validateOnly: Boolean! = false
}

input CreateSampleInput {
  proposalNumber: Int!
  instrumentSessionNumber: Int!
  samples: [SampleInLegacy!]!
  validateOnly: Boolean! = false
}

"""Return type when creating or validating samples"""
type CreateSamplesResponse {
  """Whether the operation has succeeded without validation errors"""
  success: Boolean!

  """Samples that have been created"""
  samples: [Sample!]!

  """Errors that occurred during sample validation"""
  errors: [SampleValidationError!]!
}

input DatetimeOperatorInput {
  """
  Will filter to items where the `DateTime` field is greater than (i.e. after) the provided value
  """
  gt: DateTime = null

  """
  Will filter to items where the `DateTime` field is less than (i.e. before) the provided value
  """
  lt: DateTime = null
}

"""The details of sample validation error"""
type ErrorDetails {
  """The type of error that occurred"""
  type: String!

  """
  Tuple of strings identifying where in the sample schema the error occurred.
  """
  location: [String!]!

  """A human readable error message."""
  message: String!
}

input JSONOperator @oneOf {
  stringOperator: StringOperatorInput
  datetimeOperator: DatetimeOperatorInput
  numericOperator: NumericOperatorInput
}

input JSONOperatorInput {
  """A JSON path specifying the value to filter. Must start with '$.'"""
  path: String!

  """The operator to apply to the JSON field"""
  operator: JSONOperator!
}

input NumericOperatorInput {
  """
  Will filter to items where the numeric field is greater than the provided value
  """
  gt: Float = null

  """
  Will filter to items where the numeric field is less than the provided value
  """
  lt: Float = null
}

type SampleConnection {
  edges: [SampleEdge!]!
  pageInfo: PageInfo!
}

type SampleEdge {
  cursor: String!
  node: Sample!
}

type SampleEvent {
  id: UUID!
  timestamp: DateTime!
  description: String!
}

type SampleEventConnection {
  edges: [SampleEventEdge!]!
  pageInfo: PageInfo!
}

type SampleEventEdge {
  cursor: String!
  node: SampleEvent!
}

input SampleFilterInput {
  """Filter on the `schemaUrl` field of `Sample`"""
  schemaUrl: StringOperatorInput = null

  """Filter on the `createdTime` field of `Sample`"""
  createdTime: DatetimeOperatorInput = null

  """Filter on the `createdTime` field of `Sample`"""
  updatedTime: DatetimeOperatorInput = null

  """Filter on the `name` field of `Sample`"""
  name: StringOperatorInput = null

  """Filter on the `data` field of `Sample`"""
  data: [JSONOperatorInput!] = null
}

type SampleImage {
  url: String!
  filename: String!
}

input SampleIn {
  """Name of the sample"""
  name: String!

  """Data of the sample"""
  data: JSON!
}

input SampleInLegacy {
  name: String!
  data: JSON!
  dataSchemaUrl: String!
  parentIds: [Int!] = null
  children: [SampleInLegacy!] = null
}

type SampleMutations {
  sampleId: UUID!
  updateSample(input: UpdateSampleInput!): UpdateSampleResponse!
  linkInstrumentSessionToSample(proposalNumber: Int!, instrumentSessionNumber: Int!): Void
  addSampleEvent(sampleEvent: AddSampleEventInput!): SampleEvent!
  createSampleImageUploadUrl(filename: String!, contentType: String!, contentLength: Int!): String!
}

input SampleOrder {
  name: SortingOrder = null
  createdTime: SortingOrder = null
  updatedTime: SortingOrder = null
}

"""The details of errors occurred when validating a sample"""
type SampleValidationError {
  """
  The index of the sample in CreateSampleInput.samples for which the error occurred
  """
  index: Int!

  """Errors that occurred when validating the sample"""
  errors: [ErrorDetails!]!
}

enum SortingOrder {
  ASC
  DESC
}

"""Conditions used to filter results based on the value of a String field"""
input StringOperatorInput {
  """
  Will filter to items where the `String` field is equal to the provided value
  """
  eq: String = null

  """
  Will filter to items where the `String` field is not equal to the provided value
  """
  ne: String = null

  """
  Will filter to items where the `String` field is a member of the provided value
  """
  in: [String!] = null

  """
  Will filter to items where the `String` field is not a member of the provided value
  """
  nin: [String!] = null

  """
  Will filter to items where the `String` field is contains the provided value
  """
  contains: String = null
}

input UpdateSampleInput {
  """Name of the sample"""
  name: String

  """Data of the sample"""
  data: JSON

  """URL of the JSON schema the samples' `data` should be validated against"""
  dataSchemaUrl: String
}

"""Return type when creating or validating samples"""
type UpdateSampleResponse {
  """Whether the operation has succeeded without validation errors"""
  success: Boolean!

  """Sample that has been updated"""
  sample: Sample

  """Errors that occurred during sample validation"""
  errors: [SampleValidationError!]!
}

"""Represents NULL values"""
scalar Void